### ISSUE TITLE
Fails to build on Java 11

### ISSUE THREAD

**Issue by abextm** [PresNL/pm-colors#2]
This import is unavailable on newer JDKs and will cause your plugin to fail to build when we upgrade.
https://github.com/PresNL/pm-colors/blob/master/src/main/java/com/pmcolors/ui/AddPlayerPanel.java#L35

**Comment by PresNL** [comment]
this should be resolved with https://github.com/PresNL/pm-colors/commit/7bf2cd7356ac9f56e8541d41a087df49dc21b27c
